### ISSUE TITLE
Consider making a single unified syntax

### ISSUE THREAD

**Issue by sdegutis** [H2CO3/Sparkling#32]
Several places in the language's grammar have multiple options, e.g. optional parentheses after `fn` or `for`. People like me can't make up our minds which one to use, and end up seeing this as a downside rather than a convenience. Might be worthwhile to unify the syntax and make there only be one allowed style.

**Comment by H2CO3** [comment]
Sure, I see what you mean. I'll consider removing these alternative syntaxes. In my experience, most modern programming languages tend to prefer less parentheses, which is sensible given that they are not essential in most places. The parentheses around the header of `for` loops could be just removed right away.

However, for functions, there are two syntaxes for convenience reasons. Single-expression functions are convenient to write without parentheses, e.g.:

    someArray.reduce(fn x y -> 2 * x - y, 0);

Whereby for regular function statements which designate named, stand-alone functions, the omission of parentheses looks weird – so I'd prefer

    fn foo(x, y) {
        do_lots_of_work();
        do_even_more_work();
        return result;
    }

This arguably is somewhat inconsistent, that's why I decided to allow both styles of parameter lists for both function syntaxes. Of course, the ideal would be to have only one syntax for functions, but I'm really struggling to remove the one-expression syntax, since it makes code quite cleaner.

**Comment by sdegutis** [comment]
It seems like a good idea to have a primary function syntax, and a more terse syntax for really short one-off functions like for use with map/reduce/filter/etc.

Here's a rough idea of what could also be done:

~~~
// for one-line functions:
someArray.reduce(fn { 2 * $1 - $2 }, 0);

// and for multi-line functions:
fn foo x y {
    do_lots_of_work();
    do_even_more_work();
    return result;
}
~~~

This unifies them so that the only difference is whether you specify positional parameters in the body or not. And the parentheses make it easy to see where the body of the first one ends within the function call it's placed inside of.

That said, I bet the `$n` syntax probably clashes with something else in the syntax. Just throwing this out there as a rough idea.

**Comment by H2CO3** [comment]
I've started working on the unification of the syntax in https://github.com/H2CO3/Sparkling/commit/9f291e01f6b05d2829e921d22a874673881954c4.

**Comment by sdegutis** [comment]
Closing because my opinion on programming was too fickle and your language is great.
