### ISSUE TITLE
Suggestion: add -export-dynamic (for dynld())

### ISSUE THREAD

**Issue by sgmesservey** [H2CO3/Sparkling#43]
Hello,
  I found that adding -export-dynamic to LDFLAGS in the makefile
enables dynamic module loading work, in that modules no longer
need explicit linking to libspn(.a|.so). Instead, they pick up the symbols
by the REPL binary. Similarly, if you statically link libspn.a, but use
-export-dynamic on the final binary, modules again don't need to link
against libspn. Oh, and I am using Linuxl; I don't know if it works on Darwin.

**Comment by H2CO3** [comment]
Thanks, added `-rdynamic` flag (which is directed to the driver rather than the linker itself, so it's a bit higher-level) when building on non-Darwin systems. See https://github.com/H2CO3/Sparkling/commit/e3ff58824c495a969eb96d41d89ea6306d75930f. On Darwin, the default behavior is to add all global symbols to the dynamic symbol table, therefore an equivalent of this flag would be redundant.
