### ISSUE TITLE
Question: At the start spn calls some .spn files, what they does?

### ISSUE THREAD

**Issue by ghost** [H2CO3/Sparkling#49]
@jcubic @H2CO3 @mattfenwick @sfan5 @idmitrievsky 

At the start spn calls `ast_validator.spn` and `functional.spn` files, what they does?

I know, this is a stupid question, but I can’t understand. What will happened if I remove `ast_validator.spn` and `functional.spn` files?

**Comment by jcubic** [comment]
I can only assume that those are bootstrap files for the language written in language itself. I have the same in my Scheme based lisp called LIPS, where I load scm files if you remove those it will break because I don't check if the files are there, I just assume that if someone installed the library, main files are there. If you remove those files and Sparkling assume that they are there it will probably fail with error at best. If you're lucky it will load the system with only core functionality.

**Comment by ghost** [comment]
@jcubic @H2CO3 @mattfenwick @sfan5 Also I have a question about `import`. What is the default path for .spn modules on Linux and Windows?

This is a path for modules to import them from everywhere.

**Comment by H2CO3** [comment]
@lewek Those are parts of the standard library and in particular the AST validator is for internal use in the compiler. Why would you want to remove those?
